export interface CelestialStats {
  mass: { value: string; unit: string };
  diameter: { value: string; unit: string };
  gravity: { value: string; unit: string };
  temperature: { value: string; unit: string };
  dayLength: { value: string; unit: string };
  yearLength: { value: string; unit: string };
  distanceFromSun: { value: string; unit: string };
  atmosphere: { en: string; hi: string };
}

export interface CelestialBody {
  id: string;
  name: { en: string; hi: string };
  type: { en: string; hi: string };
  tagline: { en: string; hi: string };
  description: { en: string; hi: string };
  color: string;
  gradient: string;
  ring?: boolean;
  videoId?: string; // YouTube video ID
  stats: CelestialStats;

  // Image sequence config (optional — falls back to CSS sphere if missing)
  frames?: {
    folder: string;   // e.g. "/universe/planets/earth"
    prefix: string;   // e.g. "frame-"
    total: number;    // e.g. 100
    extension: string; // e.g. "jpg"
    padLength: number; // e.g. 3
  };

  // Gallery images (static high-res shots)
  gallery?: string[];

  // Order for navigation
  order: number;
}

export const celestialBodies: CelestialBody[] = [
  {
    id: "mercury",
    order: 1,
    name: { en: "Mercury", hi: "बुध" },
    type: { en: "Rocky Planet", hi: "चट्टानी ग्रह" },
    tagline: {
      en: "The Swift Messenger of the Gods",
      hi: "देवताओं का तेज़ दूत",
    },
    description: {
      en: "Mercury is the smallest planet in our solar system and the closest to the Sun. Despite its proximity to the Sun, it's not the hottest planet — that title goes to Venus. Mercury has virtually no atmosphere, leading to extreme temperature swings between its day side (430°C) and night side (-180°C). Its surface is heavily cratered, resembling our Moon.",
      hi: "बुध हमारे सौरमंडल का सबसे छोटा ग्रह है और सूर्य के सबसे करीब है। सूर्य से निकटता के बावजूद, यह सबसे गर्म ग्रह नहीं है — वह खिताब शुक्र का है। बुध का वस्तुतः कोई वायुमंडल नहीं है, जिससे इसके दिन वाले हिस्से (430°C) और रात वाले हिस्से (-180°C) के बीच अत्यधिक तापमान का अंतर होता है।",
    },
    color: "#a0a0a0",
    gradient: "radial-gradient(circle at 35% 30%, #c8c8c8 0%, #8a8a8a 40%, #5a5a5a 80%)",
    videoId: "0KBjnNuhRHs",
    stats: {
      mass: { value: "3.30 × 10²³", unit: "kg" },
      diameter: { value: "4,879", unit: "km" },
      gravity: { value: "3.7", unit: "m/s²" },
      temperature: { value: "167", unit: "°C avg" },
      dayLength: { value: "59", unit: "Earth days" },
      yearLength: { value: "88", unit: "Earth days" },
      distanceFromSun: { value: "57.9", unit: "M km" },
      atmosphere: { en: "Virtually none — trace O₂, Na, H₂", hi: "लगभग कोई नहीं — सूक्ष्म O₂, Na, H₂" },
    },
  },
  {
    id: "venus",
    order: 2,
    name: { en: "Venus", hi: "शुक्र" },
    type: { en: "Rocky Planet", hi: "चट्टानी ग्रह" },
    tagline: {
      en: "Earth's Toxic Twin",
      hi: "पृथ्वी का जहरीला जुड़वां",
    },
    description: {
      en: "Venus is the hottest planet in our solar system, with surface temperatures reaching 465°C — hot enough to melt lead. Its thick atmosphere of carbon dioxide creates a runaway greenhouse effect. Venus rotates backward compared to most planets, and a single day on Venus lasts longer than its year. Its surface is hidden beneath permanent sulfuric acid clouds.",
      hi: "शुक्र हमारे सौरमंडल का सबसे गर्म ग्रह है, इसकी सतह का तापमान 465°C तक पहुँचता है — सीसे को पिघलाने के लिए पर्याप्त गर्म। कार्बन डाइऑक्साइड का इसका घना वायुमंडल अनियंत्रित ग्रीनहाउस प्रभाव पैदा करता है। शुक्र अधिकांश ग्रहों की तुलना में उल्टा घूमता है।",
    },
    color: "#e8a84c",
    gradient: "radial-gradient(circle at 35% 30%, #f0c060 0%, #d4903a 40%, #a06020 80%)",
    videoId: "BvXa1n9fjow",
    stats: {
      mass: { value: "4.87 × 10²⁴", unit: "kg" },
      diameter: { value: "12,104", unit: "km" },
      gravity: { value: "8.87", unit: "m/s²" },
      temperature: { value: "465", unit: "°C avg" },
      dayLength: { value: "243", unit: "Earth days" },
      yearLength: { value: "225", unit: "Earth days" },
      distanceFromSun: { value: "108.2", unit: "M km" },
      atmosphere: { en: "96.5% CO₂, 3.5% N₂ — crushing 90 atm pressure", hi: "96.5% CO₂, 3.5% N₂ — 90 atm दबाव" },
    },
  },
  {
    id: "earth",
    order: 3,
    name: { en: "Earth", hi: "पृथ्वी" },
    type: { en: "Rocky Planet", hi: "चट्टानी ग्रह" },
    tagline: {
      en: "The Pale Blue Dot — Our Home",
      hi: "नीला बिंदु — हमारा घर",
    },
    description: {
      en: "Earth is the only known planet to harbor life. Its liquid water oceans cover 71% of the surface, and its nitrogen-oxygen atmosphere is maintained by photosynthesis. A powerful magnetic field generated by its molten iron core shields the surface from deadly solar radiation. Earth's Moon stabilizes its axial tilt, creating the seasons that make complex life possible.",
      hi: "पृथ्वी एकमात्र ज्ञात ग्रह है जहाँ जीवन है। इसके तरल पानी के महासागर सतह के 71% को कवर करते हैं, और इसका नाइट्रोजन-ऑक्सीजन वायुमंडल प्रकाश संश्लेषण द्वारा बनाए रखा जाता है। इसके पिघले लोहे के कोर द्वारा उत्पन्न शक्तिशाली चुंबकीय क्षेत्र सतह को घातक सौर विकिरण से बचाता है।",
    },
    color: "#10b981",
    gradient: "radial-gradient(circle at 35% 30%, #34d399 0%, #059669 40%, #064e3b 80%)",
    videoId: "HCDVN7DCzYE",
    // Earth has the 240-frame sequence from the hero
    frames: {
      folder: "/earthview",
      prefix: "ezgif-frame-",
      total: 240,
      extension: "jpg",
      padLength: 3,
    },
    stats: {
      mass: { value: "5.97 × 10²⁴", unit: "kg" },
      diameter: { value: "12,742", unit: "km" },
      gravity: { value: "9.81", unit: "m/s²" },
      temperature: { value: "15", unit: "°C avg" },
      dayLength: { value: "24", unit: "hours" },
      yearLength: { value: "365.25", unit: "days" },
      distanceFromSun: { value: "149.6", unit: "M km" },
      atmosphere: { en: "78% N₂, 21% O₂, 1% Ar — life-sustaining", hi: "78% N₂, 21% O₂, 1% Ar — जीवन-सहायक" },
    },
  },
  {
    id: "mars",
    order: 4,
    name: { en: "Mars", hi: "मंगल" },
    type: { en: "Rocky Planet", hi: "चट्टानी ग्रह" },
    tagline: {
      en: "The Red Planet — Next Frontier",
      hi: "लाल ग्रह — अगली सीमा",
    },
    description: {
      en: "Mars is the most explored planet beyond Earth. Its red color comes from iron oxide (rust) in its soil. Mars hosts Olympus Mons, the tallest volcano in the solar system at 21.9 km, and Valles Marineris, a canyon system stretching 4,000 km. Evidence of ancient river beds suggests Mars once had liquid water. NASA and ISRO both have active missions studying Mars.",
      hi: "मंगल पृथ्वी के बाद सबसे अधिक खोजा गया ग्रह है। इसका लाल रंग इसकी मिट्टी में आयरन ऑक्साइड (जंग) से आता है। मंगल पर ओलंपस मॉन्स है, सौरमंडल का सबसे ऊंचा ज्वालामुखी (21.9 km), और वैलेस मैरिनेरिस, 4,000 km तक फैली घाटी प्रणाली। NASA और ISRO दोनों के मंगल पर सक्रिय मिशन हैं।",
    },
    color: "#ec4899",
    gradient: "radial-gradient(circle at 35% 30%, #f87171 0%, #dc2626 40%, #7f1d1d 80%)",
    videoId: "D8pnmwOXhoY",
    stats: {
      mass: { value: "6.42 × 10²³", unit: "kg" },
      diameter: { value: "6,779", unit: "km" },
      gravity: { value: "3.72", unit: "m/s²" },
      temperature: { value: "-65", unit: "°C avg" },
      dayLength: { value: "24.6", unit: "hours" },
      yearLength: { value: "687", unit: "Earth days" },
      distanceFromSun: { value: "227.9", unit: "M km" },
      atmosphere: { en: "95% CO₂, 2.7% N₂ — thin, 0.6% Earth pressure", hi: "95% CO₂, 2.7% N₂ — पतला, पृथ्वी के दबाव का 0.6%" },
    },
  },
  {
    id: "jupiter",
    order: 5,
    name: { en: "Jupiter", hi: "बृहस्पति" },
    type: { en: "Gas Giant", hi: "गैस विशाल" },
    tagline: {
      en: "The King of Planets",
      hi: "ग्रहों का राजा",
    },
    description: {
      en: "Jupiter is the largest planet in our solar system — over 1,300 Earths could fit inside it. Its Great Red Spot is a storm larger than Earth that has raged for over 350 years. Jupiter acts as a cosmic vacuum cleaner, its immense gravity deflecting asteroids and comets that might otherwise hit Earth. It has 95 known moons, including the four Galilean moons discovered in 1610.",
      hi: "बृहस्पति हमारे सौरमंडल का सबसे बड़ा ग्रह है — इसमें 1,300 से अधिक पृथ्वी समा सकती हैं। इसका ग्रेट रेड स्पॉट पृथ्वी से बड़ा तूफान है जो 350 से अधिक वर्षों से चल रहा है। बृहस्पति ब्रह्मांडीय वैक्यूम क्लीनर के रूप में कार्य करता है, इसके विशाल गुरुत्वाकर्षण से क्षुद्रग्रह और धूमकेतु विक्षेपित होते हैं।",
    },
    color: "#f59e0b",
    gradient: "radial-gradient(circle at 35% 30%, #fbbf24 0%, #d97706 35%, #92400e 70%, #5a3010 90%)",
    videoId: "PtkqwslbLY8",
    stats: {
      mass: { value: "1.90 × 10²⁷", unit: "kg" },
      diameter: { value: "139,820", unit: "km" },
      gravity: { value: "24.79", unit: "m/s²" },
      temperature: { value: "-110", unit: "°C cloud top" },
      dayLength: { value: "9.9", unit: "hours" },
      yearLength: { value: "11.86", unit: "Earth years" },
      distanceFromSun: { value: "778.5", unit: "M km" },
      atmosphere: { en: "90% H₂, 10% He — no solid surface", hi: "90% H₂, 10% He — कोई ठोस सतह नहीं" },
    },
  },
  {
    id: "saturn",
    order: 6,
    name: { en: "Saturn", hi: "शनि" },
    type: { en: "Gas Giant", hi: "गैस विशाल" },
    tagline: {
      en: "The Jewel of the Solar System",
      hi: "सौरमंडल का रत्न",
    },
    description: {
      en: "Saturn is instantly recognizable by its stunning ring system, composed of billions of chunks of ice and rock ranging from dust-sized to house-sized. The rings span 282,000 km wide but are only about 10 meters thick. Saturn is the least dense planet — it would actually float in water if you could find a bathtub big enough. Its moon Titan has a thick atmosphere and liquid methane lakes.",
      hi: "शनि अपने शानदार वलय तंत्र से तुरंत पहचाना जाता है, जो धूल से लेकर घर के आकार तक बर्फ और चट्टान के अरबों टुकड़ों से बना है। वलय 2,82,000 km चौड़े हैं लेकिन केवल लगभग 10 मीटर मोटे हैं। शनि सबसे कम घनत्व वाला ग्रह है — यह वास्तव में पानी में तैरेगा।",
    },
    color: "#a78bfa",
    gradient: "radial-gradient(circle at 35% 30%, #ddd6b0 0%, #c4a86c 40%, #8a7040 80%)",
    ring: true,
    videoId: "epZdZaEQhS0",
    stats: {
      mass: { value: "5.68 × 10²⁶", unit: "kg" },
      diameter: { value: "116,460", unit: "km" },
      gravity: { value: "10.44", unit: "m/s²" },
      temperature: { value: "-140", unit: "°C cloud top" },
      dayLength: { value: "10.7", unit: "hours" },
      yearLength: { value: "29.45", unit: "Earth years" },
      distanceFromSun: { value: "1,434", unit: "M km" },
      atmosphere: { en: "96% H₂, 3% He — wind speeds up to 1,800 km/h", hi: "96% H₂, 3% He — हवा की गति 1,800 km/h तक" },
    },
  },
  {
    id: "uranus",
    order: 7,
    name: { en: "Uranus", hi: "अरुण" },
    type: { en: "Ice Giant", hi: "बर्फ विशाल" },
    tagline: {
      en: "The Sideways Planet",
      hi: "तिरछा ग्रह",
    },
    description: {
      en: "Uranus is unique among planets — it rotates on its side with an axial tilt of 98°, likely caused by a massive collision billions of years ago. This means its poles take turns pointing directly at the Sun, creating extreme 42-year-long seasons. Uranus has a blue-green color from methane in its atmosphere. It has 28 known moons and faint rings discovered in 1977.",
      hi: "अरुण ग्रहों में अनूठा है — यह 98° के अक्षीय झुकाव के साथ अपनी तरफ घूमता है, संभवतः अरबों साल पहले एक विशाल टक्कर के कारण। इसका मतलब है कि इसके ध्रुव बारी-बारी से सीधे सूर्य की ओर इशारा करते हैं, जिससे 42 साल लंबी ऋतुएँ बनती हैं।",
    },
    color: "#06b6d4",
    gradient: "radial-gradient(circle at 35% 30%, #67e8f9 0%, #0891b2 40%, #164e63 80%)",
    ring: true,
    videoId: "m4NXbFOl7OU",
    stats: {
      mass: { value: "8.68 × 10²⁵", unit: "kg" },
      diameter: { value: "50,724", unit: "km" },
      gravity: { value: "8.87", unit: "m/s²" },
      temperature: { value: "-195", unit: "°C cloud top" },
      dayLength: { value: "17.2", unit: "hours" },
      yearLength: { value: "84", unit: "Earth years" },
      distanceFromSun: { value: "2,871", unit: "M km" },
      atmosphere: { en: "83% H₂, 15% He, 2% CH₄ — methane gives blue color", hi: "83% H₂, 15% He, 2% CH₄ — मीथेन नीला रंग देता है" },
    },
  },
  {
    id: "neptune",
    order: 8,
    name: { en: "Neptune", hi: "वरुण" },
    type: { en: "Ice Giant", hi: "बर्फ विशाल" },
    tagline: {
      en: "The Windiest World",
      hi: "सबसे तेज़ हवाओं का संसार",
    },
    description: {
      en: "Neptune is the farthest planet from the Sun and the windiest in the solar system, with jet streams reaching 2,100 km/h — faster than the speed of sound. It was the first planet found by mathematical prediction rather than observation. Neptune's deep blue color comes from methane in its atmosphere. Its largest moon, Triton, orbits backward and is likely a captured Kuiper Belt object.",
      hi: "वरुण सूर्य से सबसे दूर का ग्रह है और सौरमंडल में सबसे तेज़ हवाओं वाला, जेट स्ट्रीम 2,100 km/h तक पहुँचती हैं — ध्वनि की गति से भी तेज़। यह अवलोकन के बजाय गणितीय भविष्यवाणी द्वारा पाया गया पहला ग्रह था। इसका सबसे बड़ा चंद्रमा, ट्राइटन, उल्टा परिक्रमा करता है।",
    },
    color: "#3b82f6",
    gradient: "radial-gradient(circle at 35% 30%, #60a5fa 0%, #2563eb 40%, #1e3a5f 80%)",
    videoId: "NStn7zZKXfE",
    stats: {
      mass: { value: "1.02 × 10²⁶", unit: "kg" },
      diameter: { value: "49,244", unit: "km" },
      gravity: { value: "11.15", unit: "m/s²" },
      temperature: { value: "-200", unit: "°C cloud top" },
      dayLength: { value: "16.1", unit: "hours" },
      yearLength: { value: "164.8", unit: "Earth years" },
      distanceFromSun: { value: "4,495", unit: "M km" },
      atmosphere: { en: "80% H₂, 19% He, 1.5% CH₄ — supersonic winds", hi: "80% H₂, 19% He, 1.5% CH₄ — सुपरसोनिक हवाएँ" },
    },
  },
];

export function getCelestialBody(id: string): CelestialBody | undefined {
  return celestialBodies.find((b) => b.id === id);
}

export function getAllCelestialIds(): string[] {
  return celestialBodies.map((b) => b.id);
}
